-- MySQL Script generated by MySQL Workbench
-- 01/07/15 16:41:55
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cdcollection
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cdcollection` ;
CREATE SCHEMA IF NOT EXISTS `cdcollection` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cdcollection` ;

-- -----------------------------------------------------
-- Table `cdcollection`.`cdinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdcollection`.`cdinfo` ;

CREATE TABLE IF NOT EXISTS `cdcollection`.`cdinfo` (
  `idcdinfo` INT NOT NULL AUTO_INCREMENT,
  `nazwacd` VARCHAR(200) NOT NULL,
  `wykonawca` VARCHAR(200) NOT NULL,
  `data_dodania` DATETIME NOT NULL,
  `data_wydania` DATE NOT NULL,
  `opis` TEXT NOT NULL,
  PRIMARY KEY (`idcdinfo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
